export enum InfrastructureErrors {
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  UNABLE_TO_CONNECT_TO_DB = 'UNABLE_TO_CONNECT_TO_DB',
  CACHE_GET_ERROR = 'CACHE_GET_ERROR',
  CACHE_SET_ERROR = 'CACHE_SET_ERROR',
  TRANSACTION_ERROR = 'TRANSACTION_ERROR',
}
