version: '3.8'

services:
  jenkins:
    container_name: jenkins
    build:
      context: .
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
