export const DOMAIN_APPLICATION_SERVICE_IDENTIFIERS = {
  AUTH_SERVICE: Symbol.for('AuthService'),
};

export const DOMAIN_REPOSITORY_IDENTIFIERS = {};

export const DOMAIN_UNIT_OF_WORK_IDENTIFIERS = {};

export const DOMAIN_MAPPING_IDENTIFIERS = {};
